name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: |
        cd NyxLine.API
        dotnet restore
        
    - name: Build API
      run: |
        cd NyxLine.API
        dotnet build --no-restore
        
    - name: Build MAUI
      run: |
        cd NyxLine.MAUI
        dotnet build -f net8.0-windows10.0.19041.0
        
    - name: Test
      run: |
        cd NyxLine.API
        dotnet test --no-build --verbosity normal
        
    - name: Publish API
      if: github.ref == 'refs/heads/main'
      run: |
        cd NyxLine.API
        dotnet publish -c Release -o publish
        
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: api-artifact
        path: NyxLine.API/publish 